defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      description: "vanpak – das ist Vanja Pakaski und dein Ort für die unkomplizierte Abwicklung von Designaufträgen mit individuellem Service. Effizient, straight to the point, mit Klasse und modern in der Ausführung. Als kreative Grafiknomadin natürlich mit grossem Erfahrungsschatz im Gepäck."
      root: "/"
      lang: de
      og-locale: "de_DE"
      og-locale-alternate: "en_GB"
  -
    scope:
      path: "en"
    values:
      description: "vanpak - this is me, Vanja Pakaski, and your place for uncomplicated design orders with an individual service.  Efficient, straight to the point, classy and modern in design. A creative graphic nomad with a wealth of experience"
      root: "/en/"
      lang: en
      og-locale: "en_GB"
      og-locale-alternate: "de_DE"
